[server]
headless = true
maxUploadSize = 25
fileWatcherType = "none"
runOnSave = false
maxMessageSize = 50

[runner]
fastReruns = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#82318E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F6F9"
textColor = "#201B24"
